-- Create saved_locations table
create table saved_locations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  location_id bigint references locations(id) not null,
  unique(user_id, location_id)
);

-- Set up RLS (Row Level Security)
alter table saved_locations enable row level security;

create policy "Users can view their own saved locations"
  on saved_locations for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own saved locations"
  on saved_locations for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own saved locations"
  on saved_locations for delete
  using ( auth.uid() = user_id );
