-- Massive California Data Expansion
-- Inserts locations for North Coast, Bay Area, South Coast, Land, and Public Piers

-- REGION 1: NORTHERN CALIFORNIA
INSERT INTO locations (name, region, image, rating, reviews, catch, tidal_status, toxin_level, status, best_season, description, coordinates, tags, access_notes, phone_number) VALUES
(
    'Clam Beach County Park',
    'North Coast',
    'https://images.unsplash.com/photo-1629247087463-5c548480373d?auto=format&fit=crop&w=800&q=80',
    4.5,
    120,
    ARRAY['Razor Clams'],
    'Low Tide',
    'Caution',
    'Open',
    'Spring',
    'Wide sandy beach famous for razor clams. High toxin risk, always check CDPH hotline.',
    ARRAY[41.0001, -124.1148],
    ARRAY['Clams', 'Beach', 'Camping'],
    'Access: Frontage Road off Hwy 101. Note: Split into "North" and "South" zones with odd/even year closures.',
    '707-445-7651'
),
(
    'Humboldt Bay: South Spit',
    'North Coast',
    'https://images.unsplash.com/photo-1597886658253-272213725656?auto=format&fit=crop&w=800&q=80',
    4.6,
    85,
    ARRAY['Gaper Clams', 'Crabs'],
    'Low Tide',
    'Safe',
    'Open',
    'Year-round',
    'A narrow strip of dunes separating the bay from the ocean. Excellent for Gaper clams.',
    ARRAY[40.7533, -124.3133],
    ARRAY['Clams', 'Crabbing', 'Dunes'],
    'Access: South Spit Road. Note: Huge Gaper clams (requires shovel).',
    '707-445-7651'
),
(
    'Humboldt Bay: Clam Island',
    'North Coast',
    'https://images.unsplash.com/photo-1589308107660-848419614457?auto=format&fit=crop&w=800&q=80',
    4.7,
    45,
    ARRAY['Littleneck Clams', 'Washington Clams'],
    'Low Tide',
    'Safe',
    'Open',
    'Year-round',
    'Accessible only by boat or kayak. Rich clam beds in the middle of the bay.',
    ARRAY[40.7356, -124.2303],
    ARRAY['Boat Access', 'Clams', 'Kayak'],
    'Access: Boat/Kayak access only (middle of bay).',
    '707-445-7651'
),
(
    'Bodega Bay: Spud Point',
    'North Coast',
    'https://images.unsplash.com/photo-1566324677273-047720953331?auto=format&fit=crop&w=800&q=80',
    4.8,
    320,
    ARRAY['Dungeness Crab', 'Rock Crab'],
    'High Tide',
    'Safe',
    'Open',
    'Winter',
    'Popular marina for crabbing. Great facilities and easy access.',
    ARRAY[38.3281, -123.0586],
    ARRAY['Crabbing', 'Marina', 'Easy Access'],
    'Access: Spud Point Marina breakwater or public pier.',
    '707-875-3535'
),
(
    'Bodega Bay: Mudflats',
    'North Coast',
    'https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=800&q=80',
    4.4,
    150,
    ARRAY['Gaper Clams'],
    'Low Tide',
    'Safe',
    'Open',
    'Year-round',
    'Expansive mudflats revealed at low tide. Be prepared to get muddy.',
    ARRAY[38.3221, -123.0555],
    ARRAY['Clams', 'Mudflats', 'Waders Required'],
    'Access: Low tide mudflats near Westside Park.',
    '707-875-3540'
),
(
    'Tomales Bay: Lawson’s Landing',
    'North Coast',
    'https://images.unsplash.com/photo-1518182170546-0766aa6f6914?auto=format&fit=crop&w=800&q=80',
    4.9,
    500,
    ARRAY['Gaper Clams', 'Washington Clams'],
    'Low Tide',
    'Safe',
    'Open',
    'Year-round',
    'The #1 most popular clamming spot in CA. Private campground with easy access to sandbars.',
    ARRAY[38.2321, -122.9546],
    ARRAY['Clams', 'Camping', 'Popular'],
    'Access: Private campground (paid entry), walk to the sandbar at low tide.',
    '707-878-2443'
),
(
    'Tomales Bay: State Park',
    'North Coast',
    'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80',
    4.6,
    210,
    ARRAY['Cockles', 'Clams'],
    'Low Tide',
    'Safe',
    'Open',
    'Year-round',
    'Beautiful park with sheltered beaches. Good for cockles.',
    ARRAY[38.1327, -122.8933],
    ARRAY['Clams', 'State Park', 'Scenic'],
    'Access: Heart’s Desire Beach (Check strict park boundaries).',
    '415-669-1140'
),
(
    'Salt Point State Park',
    'North Coast',
    'https://images.unsplash.com/photo-1502085671122-2d218cd434e6?auto=format&fit=crop&w=800&q=80',
    4.8,
    280,
    ARRAY['Mussels', 'Seaweed', 'Mushrooms'],
    'Low Tide',
    'Safe',
    'Open',
    'Fall',
    'Rugged coastline with rich intertidal life. Only State Park allowing mushroom foraging.',
    ARRAY[38.5933, -123.3467],
    ARRAY['Mussels', 'Mushrooms', 'Seaweed'],
    'Access: Fisk Mill Cove or Gerstle Cove. Note: Only State Park that allows mushroom foraging too.',
    '707-847-3221'
),
(
    'Glass Beach / Fort Bragg',
    'North Coast',
    'https://images.unsplash.com/photo-1535025639604-9a804c092faa?auto=format&fit=crop&w=800&q=80',
    4.5,
    400,
    ARRAY['Seaweed', 'Nori', 'Kombu'],
    'Low Tide',
    'Safe',
    'Open',
    'Summer',
    'Famous for sea glass, but also a prime spot for harvesting seaweed.',
    ARRAY[39.4536, -123.8136],
    ARRAY['Seaweed', 'Beach', 'Scenic'],
    'Access: Rocky intertidal zones. Bull Kelp harvesting is popular here.',
    '707-961-2800'
);

-- REGION 1: LAND FORAGING
INSERT INTO locations (name, region, image, rating, reviews, catch, tidal_status, toxin_level, status, best_season, description, coordinates, tags, access_notes, phone_number) VALUES
(
    'Jackson Demonstration State Forest',
    'North Coast',
    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80',
    4.8,
    150,
    ARRAY['Chanterelles', 'Candy Caps'],
    'N/A',
    'Safe',
    'Permit Required',
    'Winter',
    'Vast redwood forest offering excellent mushroom hunting.',
    ARRAY[39.3925, -123.6490],
    ARRAY['Mushrooms', 'Forest', 'Hiking'],
    'Permit Required: Buy from CalFire in Fort Bragg. Note: Logging roads off Hwy 20.',
    '707-964-5674'
),
(
    'King Range (Lost Coast)',
    'North Coast',
    'https://images.unsplash.com/photo-1463693396721-8ca0cfa2b3b5?auto=format&fit=crop&w=800&q=80',
    4.9,
    90,
    ARRAY['Huckleberries', 'Blackberries'],
    'N/A',
    'Safe',
    'Open',
    'Summer',
    'Remote and wild. Abundant berries in late summer.',
    ARRAY[40.1582, -124.1677],
    ARRAY['Berries', 'Wilderness', 'Hiking'],
    'Access: Shelter Cove Road.',
    '707-986-5400'
);

-- REGION 2: BAY AREA & CENTRAL COAST
INSERT INTO locations (name, region, image, rating, reviews, catch, tidal_status, toxin_level, status, best_season, description, coordinates, tags, access_notes, phone_number) VALUES
(
    'Pillar Point Harbor',
    'Bay Area',
    'https://images.unsplash.com/photo-1565627248375-3e70f6d6ce39?auto=format&fit=crop&w=800&q=80',
    4.7,
    450,
    ARRAY['Purple Sea Urchin', 'Mussels', 'Crab'],
    'Low Tide',
    'Safe',
    'Open',
    'Winter',
    'Urchin foraging is encouraged here to help save the kelp forests.',
    ARRAY[37.4954, -122.4987],
    ARRAY['Urchin', 'Tide Pools', 'Harbor'],
    'Access: Mavericks Beach tide pools (low tide). Note: Urchin foraging is huge here right now to save kelp.',
    '650-726-5727'
),
(
    'Half Moon Bay Jetties',
    'Bay Area',
    'https://images.unsplash.com/photo-1541795020-035071069527?auto=format&fit=crop&w=800&q=80',
    4.5,
    200,
    ARRAY['Dungeness Crab', 'Rock Crab', 'Monkeyface Prickleback'],
    'High Tide',
    'Safe',
    'Open',
    'Winter',
    'Great spot for poke poling and crabbing.',
    ARRAY[37.4994, -122.4880],
    ARRAY['Crabbing', 'Fishing', 'Jetty'],
    'Access: West Breakwater. Poke pole fishing is popular here.',
    '650-726-5727'
),
(
    'Davenport Landing',
    'Central Coast',
    'https://images.unsplash.com/photo-1471922694854-ff1b63b20054?auto=format&fit=crop&w=800&q=80',
    4.6,
    180,
    ARRAY['Mussels'],
    'Low Tide',
    'Caution',
    'Open',
    'Spring',
    'Scenic beach with mussel beds. Check toxin levels religiously.',
    ARRAY[37.0244, -122.2158],
    ARRAY['Mussels', 'Beach', 'Scenic'],
    'Access: Beach just north of town. Check Toxin Levels religiously.',
    '831-429-2850'
),
(
    'Elkhorn Slough',
    'Central Coast',
    'https://images.unsplash.com/photo-1518873890627-d4b177c06e51?auto=format&fit=crop&w=800&q=80',
    4.8,
    350,
    ARRAY['Gaper Clams'],
    'Low Tide',
    'Safe',
    'Restricted',
    'Year-round',
    'Rich estuary. Check specific reserve boundaries as many areas are protected.',
    ARRAY[36.8167, -121.7667],
    ARRAY['Clams', 'Estuary', 'Wildlife'],
    'Access: Near Moss Landing. Often restricted, check specific reserve boundaries.',
    '831-728-2822'
),
(
    'Morro Bay: Mudflats',
    'Central Coast',
    'https://images.unsplash.com/photo-1596327027827-2c2977b63706?auto=format&fit=crop&w=800&q=80',
    4.5,
    220,
    ARRAY['Grassy Rockfish', 'Ghost Shrimp'],
    'Low Tide',
    'Safe',
    'Restricted',
    'Year-round',
    'Stay in the recreational zone. Most of the bay is a strict reserve.',
    ARRAY[35.3464, -120.8432],
    ARRAY['Fishing', 'Bait', 'Bay'],
    'Access: State Park Marina area. Most of the bay is a strict reserve, stay in the recreational zone.',
    '805-772-2560'
),
(
    'Pismo Beach',
    'Central Coast',
    'https://images.unsplash.com/photo-1562351748-0383353a2583?auto=format&fit=crop&w=800&q=80',
    4.7,
    600,
    ARRAY['Pismo Clams'],
    'Low Tide',
    'Safe',
    'Open',
    'Winter',
    'Famous for Pismo Clams. Strict 4.5" size limit and must have calipers.',
    ARRAY[35.1064, -120.6269],
    ARRAY['Clams', 'Beach', 'Driving'],
    'Access: South of Grand Ave (drive on beach). Note: Must have calipers. 4.5" size limit strict.',
    '805-773-7000'
),
(
    'Avila Beach',
    'Central Coast',
    'https://images.unsplash.com/photo-1606248896172-2d1297e5486e?auto=format&fit=crop&w=800&q=80',
    4.6,
    400,
    ARRAY['Rock Crab'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'No license needed on the pier.',
    ARRAY[35.1695, -120.7546],
    ARRAY['Crabbing', 'Pier', 'Family Friendly'],
    'Access: Port San Luis Pier (No license needed on pier).',
    '805-595-5400'
);

-- REGION 2: LAND FORAGING
INSERT INTO locations (name, region, image, rating, reviews, catch, tidal_status, toxin_level, status, best_season, description, coordinates, tags, access_notes, phone_number) VALUES
(
    'American River Parkway',
    'Central Valley',
    'https://images.unsplash.com/photo-1596136675960-46636836100c?auto=format&fit=crop&w=800&q=80',
    4.5,
    300,
    ARRAY['Blackberries'],
    'N/A',
    'Safe',
    'Open',
    'Summer',
    'Invasive Himalayan Blackberries are everywhere along the bike trails.',
    ARRAY[38.6221, -121.3033],
    ARRAY['Berries', 'Urban', 'Bike Trail'],
    'Access: Bike trails in Sacramento/Rancho Cordova. Invasive Himalayan Blackberries are everywhere.',
    '916-875-6961'
),
(
    'Delta Sloughs (Isleton)',
    'Central Valley',
    'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=800&q=80',
    4.4,
    120,
    ARRAY['Crayfish'],
    'N/A',
    'Safe',
    'Open',
    'Summer',
    'Catch invasive Red Swamp Crayfish in the slow-moving sloughs.',
    ARRAY[38.1620, -121.6092],
    ARRAY['Crayfish', 'River', 'Fishing'],
    'Access: Levees and slow-moving sloughs. Invasive Red Swamp Crayfish.',
    '916-777-7770'
);

-- REGION 3: SOUTHERN CALIFORNIA
INSERT INTO locations (name, region, image, rating, reviews, catch, tidal_status, toxin_level, status, best_season, description, coordinates, tags, access_notes, phone_number) VALUES
(
    'Santa Monica Bay',
    'South Coast',
    'https://images.unsplash.com/photo-1534234828563-025317354313?auto=format&fit=crop&w=800&q=80',
    4.6,
    800,
    ARRAY['Grunion'],
    'High Tide',
    'Safe',
    'Open',
    'Spring',
    'Catch Grunion by hand during full moon runs (Mar-Aug).',
    ARRAY[34.0086, -118.4986],
    ARRAY['Grunion', 'Beach', 'Night'],
    'Access: Any sandy beach during full moon runs (Mar-Aug).',
    '310-458-8300'
),
(
    'Goleta Beach Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1611006836636-23c9595e8068?auto=format&fit=crop&w=800&q=80',
    4.5,
    350,
    ARRAY['Rock Crab', 'Spider Crab'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Public pier with good crabbing.',
    ARRAY[34.4147, -119.8378],
    ARRAY['Crabbing', 'Pier', 'Easy Access'],
    'Access: Public Pier.',
    '805-729-7508'
),
(
    'Malibu / Zuma Beach',
    'South Coast',
    'https://images.unsplash.com/photo-1520699697851-3dc68aa3a474?auto=format&fit=crop&w=800&q=80',
    4.7,
    600,
    ARRAY['Spiny Lobster'],
    'N/A',
    'Safe',
    'Open',
    'Winter',
    'Prime spot for lobster diving or hoop netting. Requires Lobster Report Card.',
    ARRAY[34.0204, -118.8305],
    ARRAY['Lobster', 'Diving', 'Beach'],
    'Access: Diving or Hoop Netting (requires Lobster Report Card).',
    '310-457-2525'
),
(
    'Mission Bay Jetties',
    'South Coast',
    'https://images.unsplash.com/photo-1561577553-614073f1463c?auto=format&fit=crop&w=800&q=80',
    4.6,
    450,
    ARRAY['Spiny Lobster', 'Rock Crab'],
    'N/A',
    'Safe',
    'Open',
    'Winter',
    'Popular jetty for lobster and crab.',
    ARRAY[32.7684, -117.2395],
    ARRAY['Lobster', 'Crabbing', 'Jetty'],
    'Access: Mission Bay Jetty.',
    '619-221-8899'
),
(
    'San Diego Bay',
    'South Coast',
    'https://images.unsplash.com/photo-1518659682776-0240ee422d2c?auto=format&fit=crop&w=800&q=80',
    4.7,
    500,
    ARRAY['Spotted Bay Bass', 'Bonefish'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Great fishing from Shelter Island Pier.',
    ARRAY[32.7115, -117.2281],
    ARRAY['Fishing', 'Bay', 'Pier'],
    'Access: Shelter Island Pier.',
    '619-686-6200'
),
(
    'Carlsbad / Encinitas',
    'South Coast',
    'https://images.unsplash.com/photo-1590176703565-30048e7727e0?auto=format&fit=crop&w=800&q=80',
    4.4,
    300,
    ARRAY['Mussels (Bait Only)'],
    'Low Tide',
    'Unsafe',
    'Restricted',
    'Year-round',
    'Do not eat bivalves from SoCal mainland due to urban runoff. Use for bait only.',
    ARRAY[33.1474, -117.3455],
    ARRAY['Mussels', 'Bait', 'Caution'],
    'Note: Do not eat bivalves from SoCal mainland due to urban runoff. Use for bait only.',
    '760-438-3143'
);

-- REGION 3: LAND FORAGING
INSERT INTO locations (name, region, image, rating, reviews, catch, tidal_status, toxin_level, status, best_season, description, coordinates, tags, access_notes, phone_number) VALUES
(
    'Cleveland National Forest',
    'South Coast',
    'https://images.unsplash.com/photo-1594497632662-a521456208c9?auto=format&fit=crop&w=800&q=80',
    4.6,
    200,
    ARRAY['Prickly Pear'],
    'N/A',
    'Safe',
    'Open',
    'Summer',
    'Harvest cactus fruit (Prickly Pear) along hiking trails. Wear thick gloves.',
    ARRAY[33.3392, -116.7869],
    ARRAY['Cactus', 'Hiking', 'Inland'],
    'Access: Hiking trails inland. Wear thick gloves.',
    '858-673-6180'
),
(
    'Urban Canyons (San Diego)',
    'South Coast',
    'https://images.unsplash.com/photo-1584650549926-25a472944b56?auto=format&fit=crop&w=800&q=80',
    4.5,
    150,
    ARRAY['Wild Fennel', 'Nasturtium'],
    'N/A',
    'Safe',
    'Open',
    'Spring',
    'Forage for greens in the urban canyons like Tecolote.',
    ARRAY[32.7925, -117.1869],
    ARRAY['Greens', 'Urban', 'Hiking'],
    'Access: Tecolote Canyon, Penasquitos.',
    '858-581-9944'
);

-- THE "FREE PASS" LIST (Public Piers)
INSERT INTO locations (name, region, image, rating, reviews, catch, tidal_status, toxin_level, status, best_season, description, coordinates, tags, is_public_pier, access_notes) VALUES
(
    'Crescent City: B Street Pier',
    'North Coast',
    'https://images.unsplash.com/photo-1549643276-fbc2f49277d4?auto=format&fit=crop&w=800&q=80',
    4.4,
    80,
    ARRAY['Crab', 'Rockfish'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'No fishing license required on this public pier.',
    ARRAY[41.7445, -124.1975],
    ARRAY['Pier', 'No License', 'Crabbing'],
    true,
    'Public Pier - No License Required'
),
(
    'Trinidad Pier',
    'North Coast',
    'https://images.unsplash.com/photo-1605218457336-92748b692929?auto=format&fit=crop&w=800&q=80',
    4.7,
    120,
    ARRAY['Crab', 'Rockfish'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Scenic pier with good crabbing. No license needed.',
    ARRAY[41.0547, -124.1468],
    ARRAY['Pier', 'No License', 'Scenic'],
    true,
    'Public Pier - No License Required'
),
(
    'Pacifica Pier',
    'Bay Area',
    'https://images.unsplash.com/photo-1534970028765-38ce47ef7d8d?auto=format&fit=crop&w=800&q=80',
    4.6,
    500,
    ARRAY['Dungeness Crab', 'Salmon'],
    'N/A',
    'Safe',
    'Open',
    'Winter',
    'Famous for Dungeness Crab. Crowded but productive. No license needed.',
    ARRAY[37.6333, -122.4943],
    ARRAY['Pier', 'No License', 'Crabbing'],
    true,
    'Public Pier - No License Required'
),
(
    'Santa Cruz Wharf',
    'Central Coast',
    'https://images.unsplash.com/photo-1520483601560-389dff434fdf?auto=format&fit=crop&w=800&q=80',
    4.8,
    1200,
    ARRAY['Rockfish', 'Mackerel'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Longest pier on the coast. Great amenities and fishing. No license needed.',
    ARRAY[36.9602, -122.0200],
    ARRAY['Pier', 'No License', 'Family Friendly'],
    true,
    'Public Pier - No License Required'
),
(
    'Capitola Wharf',
    'Central Coast',
    'https://images.unsplash.com/photo-1518182170546-0766aa6f6914?auto=format&fit=crop&w=800&q=80',
    4.7,
    800,
    ARRAY['Halibut', 'Perch'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Charming wharf in a colorful village. No license needed.',
    ARRAY[36.9702, -121.9536],
    ARRAY['Pier', 'No License', 'Scenic'],
    true,
    'Public Pier - No License Required'
),
(
    'Pismo Beach Pier',
    'Central Coast',
    'https://images.unsplash.com/photo-1562351748-0383353a2583?auto=format&fit=crop&w=800&q=80',
    4.8,
    900,
    ARRAY['Perch', 'Mackerel'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Iconic pier in Pismo Beach. No license needed.',
    ARRAY[35.1381, -120.6447],
    ARRAY['Pier', 'No License', 'Iconic'],
    true,
    'Public Pier - No License Required'
),
(
    'Santa Barbara: Stearns Wharf',
    'Central Coast',
    'https://images.unsplash.com/photo-1611006836636-23c9595e8068?auto=format&fit=crop&w=800&q=80',
    4.7,
    1500,
    ARRAY['Crab', 'Mackerel'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Historic wharf with shops and fishing. No license needed.',
    ARRAY[34.4064, -119.6857],
    ARRAY['Pier', 'No License', 'Tourist'],
    true,
    'Public Pier - No License Required'
),
(
    'Santa Monica Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1534234828563-025317354313?auto=format&fit=crop&w=800&q=80',
    4.8,
    5000,
    ARRAY['Mackerel', 'Perch'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'World famous pier. Fishing decks at the end. No license needed.',
    ARRAY[34.0086, -118.4986],
    ARRAY['Pier', 'No License', 'Famous'],
    true,
    'Public Pier - No License Required'
),
(
    'Venice Fishing Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1520699697851-3dc68aa3a474?auto=format&fit=crop&w=800&q=80',
    4.6,
    2000,
    ARRAY['Halibut', 'Shark'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Dedicated fishing pier. No license needed.',
    ARRAY[33.9778, -118.4692],
    ARRAY['Pier', 'No License', 'Fishing'],
    true,
    'Public Pier - No License Required'
),
(
    'Manhattan Beach Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1565627248375-3e70f6d6ce39?auto=format&fit=crop&w=800&q=80',
    4.8,
    1800,
    ARRAY['Perch', 'Mackerel'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Beautiful pier with an aquarium at the end. No license needed.',
    ARRAY[33.8837, -118.4136],
    ARRAY['Pier', 'No License', 'Aquarium'],
    true,
    'Public Pier - No License Required'
),
(
    'Newport Beach: Balboa Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1590176703565-30048e7727e0?auto=format&fit=crop&w=800&q=80',
    4.7,
    1200,
    ARRAY['Mackerel', 'Bonito'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Popular for mackerel fishing. No license needed.',
    ARRAY[33.6009, -117.9001],
    ARRAY['Pier', 'No License', 'Fishing'],
    true,
    'Public Pier - No License Required'
),
(
    'Newport Beach: Newport Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1561577553-614073f1463c?auto=format&fit=crop&w=800&q=80',
    4.6,
    1100,
    ARRAY['Mackerel', 'Sculpin'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Located near the Dory Fleet market. No license needed.',
    ARRAY[33.6075, -117.9288],
    ARRAY['Pier', 'No License', 'Market'],
    true,
    'Public Pier - No License Required'
),
(
    'San Diego: Ocean Beach Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1518659682776-0240ee422d2c?auto=format&fit=crop&w=800&q=80',
    4.7,
    2500,
    ARRAY['Lobster', 'Bass'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Longest concrete pier on the West Coast. No license needed.',
    ARRAY[32.7487, -117.2561],
    ARRAY['Pier', 'No License', 'Longest'],
    true,
    'Public Pier - No License Required'
),
(
    'San Diego: Crystal Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1584650549926-25a472944b56?auto=format&fit=crop&w=800&q=80',
    4.8,
    1500,
    ARRAY['Perch', 'Corbina'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Pier with cottages on it. Fishing allowed. No license needed.',
    ARRAY[32.7959, -117.2584],
    ARRAY['Pier', 'No License', 'Cottages'],
    true,
    'Public Pier - No License Required'
),
(
    'San Diego: Imperial Beach Pier',
    'South Coast',
    'https://images.unsplash.com/photo-1594497632662-a521456208c9?auto=format&fit=crop&w=800&q=80',
    4.5,
    800,
    ARRAY['Croaker', 'Mackerel'],
    'N/A',
    'Safe',
    'Open',
    'Year-round',
    'Southernmost pier in California. No license needed.',
    ARRAY[32.5783, -117.1172],
    ARRAY['Pier', 'No License', 'South'],
    true,
    'Public Pier - No License Required'
);
