-- Enable the PostGIS extension for location queries (optional but good for future)
create extension if not exists postgis;

-- Create locations table
create table locations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  region text not null,
  image text,
  rating numeric,
  reviews integer,
  catch text[], -- Array of strings
  tidal_status text,
  toxin_level text,
  status text,
  best_season text,
  description text,
  coordinates numeric[], -- Array of numbers [lat, lng]
  tags text[] -- Array of strings
);

-- Create species table
create table species (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  scientific_name text,
  image text,
  season text,
  edibility text,
  description text,
  habitat text
);

-- Create guides table
create table guides (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  author text,
  image text,
  excerpt text,
  read_time text
);

-- Seed locations data
insert into locations (name, region, image, rating, reviews, catch, tidal_status, toxin_level, status, best_season, description, coordinates, tags)
values
  (
    'Half Moon Bay: Pillar Point',
    'California',
    'https://images.unsplash.com/photo-1663517684742-8d2df9993924?auto=format&fit=crop&w=800&q=80',
    4.8,
    850,
    ARRAY['Sea Urchin', 'Mussels', 'Kelp'],
    'Low Tide',
    'Safe',
    'Open',
    'Winter',
    'A premier spot for tide pooling and foraging. Famous for its purple sea urchins and abundant mussel beds accessible during negative tides.',
    ARRAY[37.4957, -122.4996],
    ARRAY['Tide Pools', 'Shellfish', 'Beginner Friendly']
  ),
  (
    'Puget Sound: Hood Canal',
    'Washington',
    'https://images.unsplash.com/photo-1548565495-a6925f70dd28?auto=format&fit=crop&w=800&q=80',
    4.9,
    1200,
    ARRAY['Oysters', 'Clams', 'Geoduck'],
    'Rising',
    'Safe',
    'Open',
    'Spring',
    'World-renowned for its oysters. The public beaches here offer excellent clamming and oyster picking opportunities.',
    ARRAY[47.6397, -122.9359],
    ARRAY['Oysters', 'Mud Flats', 'Permit Required']
  ),
  (
    'Maine Coast: Acadia',
    'Maine',
    'https://images.unsplash.com/photo-1505835672097-7143354f6775?auto=format&fit=crop&w=800&q=80',
    4.7,
    940,
    ARRAY['Periwinkles', 'Irish Moss', 'Mussels'],
    'High Tide',
    'Caution',
    'Open',
    'Summer',
    'Rugged coastline offering a variety of seaweeds and small mollusks. Check local red tide warnings frequently.',
    ARRAY[44.3386, -68.2733],
    ARRAY['Seaweed', 'Rocky', 'Scenic']
  ),
  (
    'Oregon Coast: Tillamook Bay',
    'Oregon',
    'https://images.unsplash.com/photo-1595252387976-20612a32d5e1?auto=format&fit=crop&w=800&q=80',
    4.8,
    1500,
    ARRAY['Dungeness Crab', 'Cockles', 'Butter Clams'],
    'Low Tide',
    'Safe',
    'Open',
    'Fall',
    'A massive bay popular for crabbing and clamming. Great for families and beginners.',
    ARRAY[45.4959, -123.9387],
    ARRAY['Crabbing', 'Bay', 'Easy Access']
  ),
  (
    'Cape Cod: Wellfleet',
    'Massachusetts',
    'https://images.unsplash.com/photo-1504564396566-1c71546c0c32?auto=format&fit=crop&w=800&q=80',
    4.9,
    2100,
    ARRAY['Oysters', 'Quahogs', 'Razor Clams'],
    'Low Tide',
    'Safe',
    'Open',
    'Fall',
    'Famous for the Wellfleet Oyster. Extensive tidal flats make for productive foraging.',
    ARRAY[41.9301, -70.0311],
    ARRAY['Oysters', 'Flats', 'Iconic']
  ),
  (
    'Bodega Bay',
    'California',
    'https://images.unsplash.com/photo-1473442240418-4521629be2ce?auto=format&fit=crop&w=800&q=80',
    4.6,
    780,
    ARRAY['Red Rock Crab', 'Clams', 'Sea Lettuce'],
    'Rising',
    'Unsafe',
    'Closed',
    'Winter',
    'A popular spot for crabbing off the jetty and clamming in the mudflats. Currently closed due to domoic acid.',
    ARRAY[38.3333, -123.0481],
    ARRAY['Crabbing', 'Jetty', 'Closed']
  ),
  (
    'Gulf Coast: Galveston',
    'Texas',
    'https://images.unsplash.com/photo-1621523520170-634aa54bd37d?auto=format&fit=crop&w=800&q=80',
    4.5,
    1100,
    ARRAY['Blue Crab', 'Oysters'],
    'High Tide',
    'Safe',
    'Open',
    'Spring',
    'Warm waters rich in Blue Crab. Accessible from piers and marshes.',
    ARRAY[29.3013, -94.7977],
    ARRAY['Blue Crab', 'Warm Water', 'Pier']
  ),
  (
    'Alaska: Kachemak Bay',
    'Alaska',
    'https://images.unsplash.com/photo-1551720956-4134f9512641?auto=format&fit=crop&w=800&q=80',
    5.0,
    450,
    ARRAY['Razor Clams', 'Halibut', 'Salmon'],
    'Low Tide',
    'Safe',
    'Open',
    'Summer',
    'A pristine wilderness offering some of the best cold-water foraging in the world.',
    ARRAY[59.6126, -151.4256],
    ARRAY['Wilderness', 'Cold Water', 'Abundant']
  );

-- Seed species data
insert into species (name, scientific_name, image, season, edibility, description, habitat)
values
  (
    'Purple Sea Urchin',
    'Strongylocentrotus purpuratus',
    'https://images.unsplash.com/photo-1550949006-567565d03d4b?auto=format&fit=crop&w=800&q=80',
    'Winter - Spring',
    'Choice (Uni)',
    'Spiny purple echinoderm found in rocky intertidal zones. The gonads (uni) are a delicacy.',
    'Rocky tide pools, kelp forests.'
  ),
  (
    'Pacific Razor Clam',
    'Siliqua patula',
    'https://images.unsplash.com/photo-1620634272982-63c133278822?auto=format&fit=crop&w=800&q=80',
    'Fall - Spring',
    'Choice Edible',
    'Large, oblong clam with a brittle shell. Requires fast digging in sandy beaches.',
    'Sandy surf beaches.'
  ),
  (
    'Bull Kelp',
    'Nereocystis luetkeana',
    'https://images.unsplash.com/photo-1559654424-2c559344a735?auto=format&fit=crop&w=800&q=80',
    'Summer',
    'Edible (Pickles)',
    'Large brown algae with a floating bulb. Stipes make excellent pickles.',
    'Subtidal rocky zones.'
  ),
  (
    'Dungeness Crab',
    'Metacarcinus magister',
    'https://images.unsplash.com/photo-1562592282-351547471265?auto=format&fit=crop&w=800&q=80',
    'Winter',
    'Choice Edible',
    'Prized crab with sweet meat. Requires a trap or hoop net.',
    'Sandy or muddy bottoms, eelgrass beds.'
  );

-- Seed guides data
insert into guides (title, author, image, excerpt, read_time)
values
  (
    'Tide Pooling Etiquette',
    'Marine Biologist',
    'https://images.unsplash.com/photo-1566550367077-3339a923c459?auto=format&fit=crop&w=800&q=80',
    'Walk gently, touch carefully, and put everything back where you found it.',
    '5 min read'
  ),
  (
    'Identifying Toxic Algae',
    'Safety First',
    'https://images.unsplash.com/photo-1621961048738-b85c34603b41?auto=format&fit=crop&w=800&q=80',
    'How to spot red tides and check the biotoxin hotline before you go.',
    '8 min read'
  ),
  (
    'How to Clean Clams',
    'Chef Forager',
    'https://images.unsplash.com/photo-1599251412782-833d0492a080?auto=format&fit=crop&w=800&q=80',
    'Purging sand and preparing your catch for the pot.',
    '6 min read'
  );
